services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    image: web
    command: sh -c "PYTHONPATH=. streamlit run Home.py --server.port 8501"
    volumes:
      - type: bind
        source: ./data
        target: /data
        bind:
          create_host_path: true
    ports:
      - 8501:8501
    restart: unless-stopped
    depends_on:
      - "backend"
    networks:
      - vnet


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--log-level", "info", "--reload"]
    env_file: ./backend/.env
    volumes:
      - type: bind
        source: ./backend/src
        target: /module/src
      - type: bind
        source: ./data
        target: /data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - "ollama"
      - "milvus"
    networks:
      - vnet

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    ports:
      - 11434:11434
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
        bind:
          create_host_path: true
      - type: bind
        source: ../volumes/ollama
        target: /root/.ollama
        bind:
          create_host_path: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["env", "LLM_NAME=llama3.1", "/bin/sh", "/scripts/run-ollama.sh"]
    networks:
      - vnet

  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - type: bind
        source: ./volumes/etcd
        target: /etcd
        bind:
          create_host_path: true
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: unless-stopped
    networks:
      - vnet

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9001
      - 9000
    volumes:
      - type: bind
        source: ./volumes/minio
        target: /minio_data
        bind:
          create_host_path: true
    command: minio server /minio_data --console-address ":9001"
    restart: unless-stopped
    networks:
      - vnet

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.4.10
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - type: bind
        source: ./volumes/milvus
        target: /var/lib/milvus
        bind:
          create_host_path: true
    ports:
      - 19530:19530
      - 9091
    depends_on:
      - "etcd"
      - "minio"
    restart: unless-stopped
    networks:
      - vnet

networks:
  vnet:
